/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author Otros
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVaunas
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menú principal - Sistema de Vacunación");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        popUp = new javax.swing.JPopupMenu();
        ventanaEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        vacunas = new javax.swing.JMenuItem();
        vacunadores = new javax.swing.JMenuItem();
        vacunados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mostrarVacunas = new javax.swing.JMenuItem();
        mostrarVacunadores = new javax.swing.JMenuItem();
        mostrarVacunados = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        popUp.setInvoker(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout ventanaEscritorioLayout = new javax.swing.GroupLayout(ventanaEscritorio);
        ventanaEscritorio.setLayout(ventanaEscritorioLayout);
        ventanaEscritorioLayout.setHorizontalGroup(
            ventanaEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        ventanaEscritorioLayout.setVerticalGroup(
            ventanaEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jMenu1.setText("Ingresar Datos");

        vacunas.setText("Vacunas");
        vacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacunasActionPerformed(evt);
            }
        });
        jMenu1.add(vacunas);

        vacunadores.setText("Vacunadores");
        vacunadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacunadoresActionPerformed(evt);
            }
        });
        jMenu1.add(vacunadores);

        vacunados.setText("Vacunados");
        vacunados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacunadosActionPerformed(evt);
            }
        });
        jMenu1.add(vacunados);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver Datos");

        mostrarVacunas.setText("Vacunas");
        mostrarVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarVacunasActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarVacunas);

        mostrarVacunadores.setText("Vacunadores");
        mostrarVacunadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarVacunadoresActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarVacunadores);

        mostrarVacunados.setText("Vacunados");
        mostrarVacunados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarVacunadosActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarVacunados);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Funciones extras");

        jMenuItem2.setText("Vacunadores disponibles...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Listar vacunados por...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacunasActionPerformed
        VentanaNVacunas ventanaNVacunas = new VentanaNVacunas();
        ventanaNVacunas.setClosable(true);
        ventanaEscritorio.add(ventanaNVacunas);
        ventanaNVacunas.setVisible(true);
    }//GEN-LAST:event_vacunasActionPerformed

    private void mostrarVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarVacunasActionPerformed
        VentanaVacunas ventanaVacunas = new VentanaVacunas();
        ventanaVacunas.setClosable(true);
        ventanaEscritorio.add(ventanaVacunas);
        ventanaVacunas.setVisible(true);  
    }//GEN-LAST:event_mostrarVacunasActionPerformed

    private void mostrarVacunadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarVacunadosActionPerformed
        VentanaVacunados ventanaVacunados = new VentanaVacunados();
        ventanaVacunados.setClosable(true);
        ventanaEscritorio.add(ventanaVacunados);
        ventanaVacunados.setVisible(true);
    }//GEN-LAST:event_mostrarVacunadosActionPerformed

    private void mostrarVacunadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarVacunadoresActionPerformed
        VentanaVacunadores ventanaVacunadores = new VentanaVacunadores();
        ventanaVacunadores.setClosable(true);
        ventanaEscritorio.add(ventanaVacunadores);
        ventanaVacunadores.setVisible(true);
    }//GEN-LAST:event_mostrarVacunadoresActionPerformed

    private void vacunadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacunadoresActionPerformed
        VentanaNVacunador VNV = new VentanaNVacunador();
        VNV.setClosable(true);
        ventanaEscritorio.add(VNV);
        VNV.setVisible(true);
    }//GEN-LAST:event_vacunadoresActionPerformed

    private void vacunadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacunadosActionPerformed
        VentanaNVacunado VNV = new VentanaNVacunado();
        VNV.setClosable(true);
        ventanaEscritorio.add(VNV);
        VNV.setVisible(true);
    }//GEN-LAST:event_vacunadosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ListadoVacunadores lv = new ListadoVacunadores();
        lv.setVisible(true);
        lv.toFront();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ListadoVacunados lv = new ListadoVacunados();
        lv.setVisible(true);
        lv.toFront();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mostrarVacunadores;
    private javax.swing.JMenuItem mostrarVacunados;
    private javax.swing.JMenuItem mostrarVacunas;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JMenuItem vacunadores;
    private javax.swing.JMenuItem vacunados;
    private javax.swing.JMenuItem vacunas;
    public javax.swing.JDesktopPane ventanaEscritorio;
    // End of variables declaration//GEN-END:variables
}
