/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import excepciones.PersistenciaException;
import excepciones.VacunadorException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.FachadaLogica;
import logica.Vacunador;
import logica.Vacunadores;
import persistencia.PersistenciaVacunador;




/**
 *
 * @author Otros
 */
public class VentanaVacunadores extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaVacunadores
     */
    public VentanaVacunadores() {
        initComponents();
        mostrarVacunador();
    }
    
    public void mostrarVacunador(){
        DefaultTableModel tVacunador = new DefaultTableModel();
        PersistenciaVacunador pvacunador = new PersistenciaVacunador();
        Vacunadores vacunadores = null;
        try {
            vacunadores = pvacunador.consultar();
        } catch (VacunadorException ex) {
            Logger.getLogger(VentanaVacunadores.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (PersistenciaException ex) {
            Logger.getLogger(VentanaVacunadores.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        tVacunador.addColumn("Codigo");
        tVacunador.addColumn("Nombre");
        tVacunador.addColumn("Turno");
        int i = 0;
        while (i < vacunadores.getVacunadores().size()) {
            Vacunador vacuna = new Vacunador();
            vacuna = vacunadores.getVacunadores().get(i);
            String[] fila = new String[3];
            fila[0] = String.valueOf(vacuna.getCodigo());
            fila[1] = vacuna.getNombre();
            if (vacuna.getTurno()== 0) {
                fila[2] = "Mañana";
            } else {
                fila[2] = "Tarde";
            }
            tVacunador.addRow(fila);
            i++;
        }
        this.tblVacunadores.setModel(tVacunador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVacunadores = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vacunadores");

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        tblVacunadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVacunadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(modificar)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrar)
                    .addComponent(modificar))
                .addGap(9, 9, 9))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if (tblVacunadores.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else if(tblVacunadores.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una sola fila");
        }else{
            DefaultTableModel modelo = (DefaultTableModel) tblVacunadores.getModel(); 
            
            //cargo
            Vacunadores vacunador = new Vacunadores();
            vacunador.setCodigo(Integer.parseInt ((String) modelo.getValueAt(tblVacunadores.getSelectedRow(), 0)));
            vacunador.setNombre((String) modelo.getValueAt(tblVacunadores.getSelectedRow(), 1));
            if("Mañana".equals((String) modelo.getValueAt(tblVacunadores.getSelectedRow(), 2))){
                vacunador.setTurno(0);
            }else{
                vacunador.setTurno(1);
            }
            
            //envio
            VentanaMVacunador vmv = new VentanaMVacunador();
            vmv.toFront();
            vmv.setVisible(true);
            vmv.vacunador = vacunador;
        }        

        
    }//GEN-LAST:event_modificarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblVacunadores.getModel();
        int codigoVacunador = Integer.parseInt ((String) modelo.getValueAt(tblVacunadores.getSelectedRow(), 0));
        try {
            FachadaLogica.borrarVacunador(codigoVacunador);
        } catch (VacunadorException ex) {
            Logger.getLogger(VentanaVacunadores.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (PersistenciaException ex) {
            Logger.getLogger(VentanaVacunadores.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tblVacunadores;
    // End of variables declaration//GEN-END:variables

}
