/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import excepciones.PersistenciaException;
import excepciones.VacunasException;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.FachadaLogica;
import logica.Vacuna;
import logica.Vacunas;
import persistencia.PersistenciaVacuna;

/**
 *
 * @author Otros
 */
public class VentanaVacunas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaVacunadores
     */
    public VentanaVacunas() {
        initComponents();
        mostrarVacuna();
    }

    public void mostrarVacuna() {
        DefaultTableModel tVacuna = new DefaultTableModel();
        PersistenciaVacuna pVacunas = new PersistenciaVacuna();

        Vacunas vacunas = null;
        try {
            vacunas = pVacunas.consultar();
        } catch (VacunasException ex) {
            Logger.getLogger(VentanaVacunas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (PersistenciaException ex) {
            Logger.getLogger(VentanaVacunas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        tVacuna.addColumn("Codigo");
        tVacuna.addColumn("Nombre");
        tVacuna.addColumn("Dosis");
        tVacuna.addColumn("Vencimiento");
        tVacuna.addColumn("Categoria");
        int i = 0;
        while (i < vacunas.getVacunas().size()) {
            Vacuna vacuna = new Vacuna();
            vacuna = vacunas.getVacunas().get(i);
            String[] fila = new String[5];
            Date[] fila2 = new Date[4];
            fila[0] = String.valueOf(vacuna.getCodigo());
            fila[1] = vacuna.getNombre();
            fila[2] = String.valueOf(vacuna.getCantidadDosis());
            fila2[3] = Date.valueOf(vacuna.getFechaVencimiento().toLocalDate());
            
            if (vacuna.getCategoria() == 0) {
                fila[4] = "Unidosis";
            } else {
                fila[4] = "Multidosis";
            }
            tVacuna.addRow(fila);
            tVacuna.addRow(fila2);
            i++;
        }
        this.tblDatos.setModel(tVacuna);
    }
    //public void 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vacunas");

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                        .addComponent(modificar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrar)
                    .addComponent(modificar))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
        int codigoVacuna = Integer.parseInt ((String) modelo.getValueAt(tblDatos.getSelectedRow(), 0));
        try{
            FachadaLogica.borrarVacuna(codigoVacuna);
        } catch (VacunasException ex) {
            Logger.getLogger(VentanaNVacunas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());         
        } catch (PersistenciaException ex) {
            Logger.getLogger(VentanaNVacunas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_borrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if (tblDatos.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else if(tblDatos.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una sola fila");
        }else{
            DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
            
            //convierto      
            Date date = new Date(2022-04-20); //((long) modelo.getValueAt(tblDatos.getSelectedRow(), 3));
            long d = date.getTime();
            java.sql.Date fechaVencimiento = new java.sql.Date(d);     
            
            //cargo
            Vacuna vacuna = new Vacuna();

            vacuna.setCodigo(Integer.parseInt ((String) modelo.getValueAt(tblDatos.getSelectedRow(), 0)));
            vacuna.setNombre((String) modelo.getValueAt(tblDatos.getSelectedRow(), 1));
            vacuna.setCantidadDosis(Integer.parseInt ((String)  modelo.getValueAt(tblDatos.getSelectedRow(), 2)));
            vacuna.setFechaVencimiento(fechaVencimiento);
            if ("Unidosis".equals((String) modelo.getValueAt(tblDatos.getSelectedRow(), 4))){
                vacuna.setCategoria(0);
            }else{
                vacuna.setCategoria(1);
            }

            //envio
            VentanaMVacuna vmv = new VentanaMVacuna();
            vmv.toFront();
            vmv.setVisible(true); 
            vmv.vacuna = vacuna;
        }  
    }//GEN-LAST:event_modificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
