/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import excepciones.PersistenciaException;
import excepciones.VacunadoException;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.FachadaLogica;
import logica.Vacunado;
import logica.Vacunados;
import persistencia.PersistenciaVacunado;

/**
 *
 * @author Otros
 */
public class VentanaVacunados extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaVacunado
     */
    public VentanaVacunados() {
        initComponents();
        mostrarVacunado();
    }
    
    public void mostrarVacunado() {
        DefaultTableModel tVacuna = new DefaultTableModel();
        PersistenciaVacunado pVacunados = new PersistenciaVacunado();

        Vacunados vacunados = pVacunados.consultar();
        tVacuna.addColumn("Documento");
        tVacuna.addColumn("Nacionalidad");
        tVacuna.addColumn("Direccion");
        tVacuna.addColumn("Telefono");
        tVacuna.addColumn("Email");
        tVacuna.addColumn("Fecha Nacimiento");
        tVacuna.addColumn("Vacunas Otorgadas");
        int i = 0;
        while (i < vacunados.getVacunados().size()) {
            Vacunado vacuna = new Vacunado();
            vacuna = vacunados.getVacunados().get(i);
            String[] fila = new String[7];
            fila[0] = vacuna.getDocumento();
            fila[1] = vacuna.getNacionalidad();
            fila[2] = vacuna.getDireccion();
            fila[3] = vacuna.getTelefono();
            fila[4] = vacuna.getEmail();
            fila[5] = String.valueOf(vacuna.getFechaNac());
            fila[6] = String.valueOf(vacuna.getVacunas());
            tVacuna.addRow(fila);
            i++;
        }

        this.tblVacunado.setModel(tVacuna);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVacunado = new javax.swing.JTable();
        borrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Vacunados");

        tblVacunado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVacunado);

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 545, Short.MAX_VALUE)
                        .addComponent(modificar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrar)
                    .addComponent(modificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if (tblVacunado.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else if(tblVacunado.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una sola fila");
        }else{
            DefaultTableModel modelo = (DefaultTableModel) tblVacunado.getModel();
            
            //convierto      
            Date date = new Date(2000-05-10); //(Date) modelo.getValueAt(tblDatos.getSelectedRow(), 3);
            System.out.println(date);
            long d = date.getTime();
            java.sql.Date fechaNac = new java.sql.Date(d);     
            
            //cargo
            Vacunado vacunado = new Vacunado();
            vacunado.setDocumento((String) modelo.getValueAt(tblVacunado.getSelectedRow(), 0));
            vacunado.setNacionalidad((String) modelo.getValueAt(tblVacunado.getSelectedRow(), 1));
            vacunado.setDireccion((String) modelo.getValueAt(tblVacunado.getSelectedRow(), 2));
            vacunado.setTelefono((String) modelo.getValueAt(tblVacunado.getSelectedRow(), 3));
            vacunado.setEmail((String) modelo.getValueAt(tblVacunado.getSelectedRow(), 4));
            vacunado.setFechaNac(fechaNac);
            vacunado.setVacunas(Integer.parseInt ((String) modelo.getValueAt(tblVacunado.getSelectedRow(), 6)));

            //envio
            VentanaMVacunado VMV = new VentanaMVacunado();
            VMV.toFront();
            VMV.setVisible(true);
            VMV.vacunado = vacunado;
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblVacunado.getModel();
        String documento = (String) modelo.getValueAt(tblVacunado.getSelectedRow(), 0);
        try {
            FachadaLogica.borrarVacunado(documento);
            JOptionPane.showMessageDialog(null, "Eliminado con éxito");            
        } catch (VacunadoException ex) {
            Logger.getLogger(VentanaVacunados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());            
        } catch (PersistenciaException ex) {
            Logger.getLogger(VentanaVacunados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());            
        }
    }//GEN-LAST:event_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tblVacunado;
    // End of variables declaration//GEN-END:variables
}
